name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "5.0"

      - name: Testing Server
        run: |
          cd server
          npm install
          npm run test

      - name: Testing Client
        run: |
          cd ../client
          npm install
          npm run test
        
      # - name: Cypress Run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm run start:test
